version: '3.9'

services:
  client:
    build: client
    ports:
      - '3000:3000'
  sequences:
    build: sequences
    ports:
      - '4000:4000'
  dna:
    build: dna
    ports:
      - '4001:4001'
  results:
    build: results
    ports:
      - '4002:4002'
  event-bus:
    build: event-bus
  genome-db:
    image: mongo:latest
    volumes:
      - genome-data:/data/db
    ports:
      - 27017:27017
    environment:
      # yes this is not secure whatsoever
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  genome-data:
